/** @type {import('tailwindcss').Config} */
// Theme ported verbatim from the design mockups (*/code.html tailwind.config block).
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#ad00ad',
        'surface-tint': '#00e639',
        'on-tertiary-fixed-variant': '#810081',
        'on-error-container': '#ffdad6',
        'surface-bright': '#39383e',
        'secondary-fixed': '#6ff6ff',
        'on-surface': '#e4e1e9',
        surface: '#131318',
        'surface-variant': '#35343a',
        'surface-container': '#1f1f25',
        'inverse-surface': '#e4e1e9',
        'surface-container-lowest': '#0e0e13',
        'on-background': '#e4e1e9',
        'inverse-on-surface': '#303036',
        'outline-variant': '#3b4b37',
        error: '#ffb4ab',
        'primary-container': '#00ff41',
        'on-secondary-fixed': '#002022',
        secondary: '#dcfdff',
        'surface-container-high': '#2a292f',
        'secondary-container': '#00f1fd',
        'primary-fixed': '#72ff70',
        'on-secondary-fixed-variant': '#004f53',
        'error-container': '#93000a',
        'surface-container-highest': '#35343a',
        'primary-fixed-dim': '#00e639',
        'inverse-primary': '#006e16',
        'on-primary-fixed': '#002203',
        'on-tertiary-fixed': '#380038',
        'surface-container-low': '#1b1b20',
        background: '#131318',
        'tertiary-fixed': '#ffd7f5',
        primary: '#ebffe2',
        'tertiary-fixed-dim': '#ffabf3',
        'tertiary-container': '#ffcef4',
        'on-error': '#690005',
        'on-secondary': '#00373a',
        'on-tertiary': '#5b005b',
        'on-primary': '#003907',
        outline: '#84967e',
        tertiary: '#fff7f9',
        'on-primary-container': '#007117',
        'surface-dim': '#131318',
        'on-primary-fixed-variant': '#00530e',
        'on-surface-variant': '#b9ccb2',
        'secondary-fixed-dim': '#00dce6',
        'on-secondary-container': '#006a6f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        margin: '24px',
        'container-max': '1440px',
        gutter: '16px',
        unit: '4px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        display: ['JetBrains Mono', 'monospace'],
        'body-md': ['JetBrains Mono', 'monospace'],
        'body-lg': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'headline-md': ['JetBrains Mono', 'monospace'],
        code: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.05em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        code: ['13px', { lineHeight: '1.4', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
